version: "3.7"

services:
  # If you add 'node' container here, also add these lines:
  # env:
  #   - ./mongodb/.env
  # (we share Mongo's env vars like username, password, etc., with Node 
  # to be able to connect to Mongo from Node container)
  mongodb:
    container_name: mongodb
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    volumes:
      - ./mongodb/data/db/:/data/db/
      - ./mongodb/data/log/:/var/log/mongodb/
      - ./mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      - ./mongodb/mongod.conf:/etc/mongod.conf
    ports:
      - "27018:27017"
    env_file:
      - ./mongodb/.env
